### PR TITLE
[ERP-764] Prevent creating patients with the same email as carer

### PR DESCRIPTION
**Pull request by Lexiel46**
Requires trrf PR ERP-764-prevent-creating-patients-with-the-same-email-as-carer

### CODE REVIEW

**Review by ppettitau — CHANGES_REQUESTED** [review]
Ideally, the validation logic for email address should be located within the PrimaryCarerForm object. 

I have been playing around with it a bit. There's already a method on the PrimaryCarerForm to `set_patient` which provides a handle for existing patients.  You could add another method `set_patient_email` that sets the email retrieved from the request.POST parameters, if it exists (new patients). 

What do you think?

```
diff --git a/mnd/mnd/registry/patients/mnd_admin_forms.py b/mnd/mnd/registry/patients/mnd_admin_forms.py
index ebb38c6..aed2095 100644
--- a/mnd/mnd/registry/patients/mnd_admin_forms.py
+++ b/mnd/mnd/registry/patients/mnd_admin_forms.py
@@ -138,6 +138,7 @@ class PrimaryCarerForm(PrefixedModelForm):
     def __init__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)
         self.patient = None
+        self.patient_email = None
 
     @staticmethod
     def _is_valid_phone(phone_no):
@@ -171,7 +172,14 @@ class PrimaryCarerForm(PrefixedModelForm):
             return CarerRegistration.objects.has_registered_carer(instance, self.patient)
         return False
 
+
+    def set_patient_email(self, patient_email):
+        logger.info(f'patient_email: {patient_email}')
+        self.patient_email = patient_email
+
     def set_patient(self, patient):
+        logger.info('set_patient')
+        logger.info(patient.email)
         self.patient = patient
         if self.has_assigned_carer():
             for f in self.fields:
@@ -209,6 +217,20 @@ class PrimaryCarerForm(PrefixedModelForm):
         if existing_user and not existing_user.is_carer:
             raise forms.ValidationError(_("The email address is already registered into the system"))
 
+        # For demonstration purposes only, you could combine these into a single check, and remove all logging.
+        if self.patient:
+            logger.info(self.patient.email)
+
+        if self.patient_email:
+            logger.info(self.patient_email)
+
+        if self.patient_email and self.patient_email == email:
+            raise forms.ValidationError(_("Duplicate carer email 1 - new patient"))
+
+        if self.patient and self.patient.email == email:
+            raise forms.ValidationError(_("Duplicate carer email 2 - existing patient"))
+
+
         if Patient.objects.really_all().filter(email__iexact=email).exists():
             # Patient with the same email exists. Allow the change here but invites will not be sent out
             return email
diff --git a/mnd/mnd/views/mnd_patient_view.py b/mnd/mnd/views/mnd_patient_view.py
index 790cee1..9b709d4 100644
--- a/mnd/mnd/views/mnd_patient_view.py
+++ b/mnd/mnd/views/mnd_patient_view.py
@@ -27,6 +27,10 @@ def get_section(form, section_name, section_prefix, instance, request, initial=N
     if patient:
         form_instance.set_patient(patient)
 
+    if form == PrimaryCarerForm:
+        logger.info(request.POST)
+        form_instance.set_patient_email(request.POST.get('email'))
+
     section = (section_name, [f for f in form_instance.fields])
     return form_instance, (section,)
 
@@ -35,6 +39,10 @@ def get_form(form, request, prefix, instance=None, initial=None, patient=None):
     form_instance = form(request.POST, prefix=prefix, instance=instance, initial=initial or {})
     if patient:
         form_instance.set_patient(patient)
+
+    if form == PrimaryCarerForm:
+        form_instance.set_patient_email(request.POST.get('email'))
+    else:
     return form_instance
 
 

```

**Comment by ScriptSmith** [comment]
I definitely prefer keeping the logic inside the form, however I don't know about using the email value directly from the `POST` that hasn't been cleaned. It looks like we do that in a few other places for other field values, and the field will be cleaned in the patient form anyway, so maybe it's fine?

We could instead retrieve the patient email from the patient_form, however that will require passing that value to get_section and get_form.

We could also call the email validator directly in `set_patient_email`, however that will raise Exceptions, which I imagine you will have to handle.

**Comment by Lexiel46** [comment]
Tried different ways but get cleaned email data and then compare emails will always lead to some changes in the PatientEditView class in trrf patient_view.py because mnd doesn't have it's own view class. In addition, function `add_error` has to be imported to add the error message below the input after the form is validated. To make this work, the function `get_form_sections` has to be updated in both mnd_patient_view.py and patient_view.py. Would you like me to use cleaned data and make changes in both trrf and mnd patient view, or follow Paola's way to use not cleaned data and updates `PrimaryCarerForm` in mnd only? @ScriptSmith

**Comment by ScriptSmith** [comment]
Lets go without using the `cleaned_data` then, and confirm with tests that using bad values for the email field won't break things.

**Review by ppettitau — APPROVED** [review]

**Review by ScriptSmith — APPROVED** [review]

**Pull request merged**
